PedroSerapio/Models/ErrorViewModel.cs
namespace PedroSerapio.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PedroSerapio/Models/HomeModel.cs
namespace PedroSerapio.Models
{
    public class HomeModel
    {
        public string Nome { get; set; }
        public string Email { get; set; }
    }
}

PedroSerapio/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PedroSerapio.Models;
using System.Diagnostics;

namespace PedroSerapio.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            HomeModel home = new HomeModel();

            home.Nome = "Pedro";
            home.Email = "pedro@teste.pt";

            return View(home);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }

    public class DownloadController : Controller
    {
        public IActionResult DownloadCV()
        {
            var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Downloads/PedroSerápio_en.pdf");

            return PhysicalFile(filePath, "application/pdf", "PedroSerápio_en.pdf");
        }
    }
}

PedroSerapio/Views/Home/Index.cshtml
@model HomeModel
@{
    ViewData["Title"] = "Home Page";
}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<div class="text-center">
    
    <img src="/images/meDev.png" alt="me :)" class="img-fluid" />
    <h1 class="display-4" id="demo"></h1><br />
    <ul class="list-inline">
        <li class="list-inline-item">
            <a href="https://wa.me/+351969152132" class="fa fa-whatsapp"></a>
        </li>
        <li class="list-inline-item">
            <a href="tel:+351969152132" class="fa fa-phone"></a>
        </li>
        <li class="list-inline-item">
            <a href="mailto:serapio.pedro@outlook.pt" class="fa fa-envelope"></a>
        </li>
        <li class="list-inline-item">
            <a href="https://www.linkedin.com/in/pedro-serapio" class="fa fa-linkedin"></a>
        </li>
        <li class="list-inline-item">
            <a href="https://www.twitter.com/PedroSerapio" class="fa fa-twitter"></a>
        </li>


    </ul>

    <a id="projects">
    <img src="/images/underConstruction.png" alt="Under Construction" class="img-fluid" />
    </a>
    
</div>



@* This script make the effect literally write :) *@

<script>
    var i = 0;
    var txt = "Hello, I'm Pedro Serápio";
    var speed = 50;

function typeWriter() {
  if (i < txt.length) {
    document.getElementById("demo").innerHTML += txt.charAt(i);
    i++;
    setTimeout(typeWriter, speed);
  }
}
    // only proceed after DOM
    document.addEventListener('DOMContentLoaded', function () {
        typeWriter();
    });
</script>

PedroSerapio/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PedroSerapio</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PedroSerapio.styles.css" asp-append-version="true" />
</head>
<body>
    <header>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand d-none d-lg-inline" asp-area="" asp-controller="Home" asp-action="Index">Pedro Serápio</a>

            <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Home/Index#projects" >Projects</a>
                    </li>
                </ul>
                </div>
                <div class="ml-lg-auto mt-2 mt-lg-0">
                    <button type="button" class="btn btn-primary btn-sm" onclick="window.location.href='@Url.Action("DownloadCV", "Download")'">Download my CV</button>
            </div>
            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Pedro Serapio@* - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>*@
        </div>
    </footer>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <!-- jQuery primeiro, depois Popper.js, depois Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>